//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabeticsHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blood_Sugar_Range
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blood_Sugar_Range()
        {
            this.Insulin_Dosage = new HashSet<Insulin_Dosage>();
        }
    
        public int Blood_Sugar_Range_ID { get; set; }
        public float Blood_Sugar_Range_From { get; set; }
        public float Blood_Sugar_Range_To { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insulin_Dosage> Insulin_Dosage { get; set; }
    }
}
