//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabeticsHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insulin_Dosage
    {
        public long Dosage_ID { get; set; }
        public long User_ID { get; set; }
        public int Blood_Sugar_Range_ID { get; set; }
        public float Insulin_Dosage1 { get; set; }
    
        public virtual Blood_Sugar_Range Blood_Sugar_Range { get; set; }
        public virtual User User { get; set; }
    }
}
