//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabeticsHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Book
    {
        public long Log_Book_ID { get; set; }
        public long User_ID { get; set; }
        public System.DateTime Log_Date { get; set; }
        public System.TimeSpan Log_Time { get; set; }
        public float Meter_Reading { get; set; }
        public string Log_Notes { get; set; }
        public long Routine_ID { get; set; }
    
        public virtual Meal_Routine Meal_Routine { get; set; }
        public virtual User User { get; set; }
    }
}
