//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabeticsHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public long Schedule_ID { get; set; }
        public long User_ID { get; set; }
        public System.DateTime From_Date { get; set; }
        public System.DateTime To_Date { get; set; }
        public bool Active { get; set; }
    
        public virtual User User { get; set; }
    }
}
