//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabeticsHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Setting
    {
        public long Setting_ID { get; set; }
        public long User_ID { get; set; }
        public int Setting_Key { get; set; }
        public string Setting_Value { get; set; }
    
        public virtual Setting Setting { get; set; }
        public virtual User User { get; set; }
    }
}
